pygments:    false
markdown:    maruku
permalink:   /:year/:month/:day/:title.html
multiviews:  true
paginate:    10
exclude:     ['post', 'README.md', 'Gemfile*']

# plugins
category_dir: departments
category_list:
- releases
- shows
- toast-haiku
- toast-recipes
- toast-articles
- toast-news
- toast-links
- toasters
- ask-dr-toast

